"""First migration

Revision ID: 24c2462bb150
Revises: 
Create Date: 2021-04-23 21:57:05.645773

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '24c2462bb150'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('django_admin_log')
    op.drop_index('django_session_expire_date_a5c62663', table_name='django_session')
    op.drop_table('django_session')
    op.drop_index('name', table_name='auth_group')
    op.drop_table('auth_group')
    op.drop_index('auth_permission_content_type_id_codename_01ab375a_uniq', table_name='auth_permission')
    op.drop_table('auth_permission')
    op.drop_index('auth_user_user_permissions_user_id_permission_id_14a6b632_uniq', table_name='auth_user_user_permissions')
    op.drop_table('auth_user_user_permissions')
    op.drop_index('auth_user_groups_user_id_group_id_94350c0c_uniq', table_name='auth_user_groups')
    op.drop_table('auth_user_groups')
    op.drop_index('auth_group_permissions_group_id_permission_id_0cd325b0_uniq', table_name='auth_group_permissions')
    op.drop_table('auth_group_permissions')
    op.drop_index('django_content_type_app_label_model_76bd3d3b_uniq', table_name='django_content_type')
    op.drop_table('django_content_type')
    op.drop_table('django_migrations')
    op.drop_index('django_site_domain_a2e37b91_uniq', table_name='django_site')
    op.drop_table('django_site')
    op.alter_column('app_appointment', 'contact_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('app_appointment', 'created_on',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=True)
    op.alter_column('app_appointment', 'profesional_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('app_appointment', 'speciality_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_app_appointment_id'), 'app_appointment', ['id'], unique=False)
    op.alter_column('app_caja', 'created_on',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=True)
    op.alter_column('app_caja', 'monto_apertura',
               existing_type=mysql.DECIMAL(precision=7, scale=2),
               nullable=True)
    op.alter_column('app_caja', 'monto_cierre',
               existing_type=mysql.DECIMAL(precision=7, scale=2),
               nullable=True)
    op.create_index(op.f('ix_app_caja_fecha'), 'app_caja', ['fecha'], unique=False)
    op.create_index(op.f('ix_app_caja_id'), 'app_caja', ['id'], unique=False)
    op.drop_constraint('app_caja_usuario_id_f24ffaeb_fk_auth_user_id', 'app_caja', type_='foreignkey')
    op.drop_column('app_caja', 'usuario_id')
    op.alter_column('app_cajadetalle', 'caja_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('app_cajadetalle', 'monto',
               existing_type=mysql.DECIMAL(precision=7, scale=2),
               nullable=True)
    op.create_index(op.f('ix_app_cajadetalle_id'), 'app_cajadetalle', ['id'], unique=False)
    op.alter_column('app_contact', 'acceptance',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('app_contact', 'created_on',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=True)
    op.create_index(op.f('ix_app_contact_date'), 'app_contact', ['date'], unique=False)
    op.create_index(op.f('ix_app_contact_id'), 'app_contact', ['id'], unique=False)
    op.alter_column('app_invoice', 'contact_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('app_invoice', 'created_on',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=True)
    op.create_index(op.f('ix_app_invoice_id'), 'app_invoice', ['id'], unique=False)
    op.alter_column('app_invoicedetail', 'invoice_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('app_invoicedetail', 'price',
               existing_type=mysql.DECIMAL(precision=7, scale=2),
               nullable=True)
    op.alter_column('app_invoicedetail', 'product_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('app_invoicedetail', 'profesional_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_app_invoicedetail_id'), 'app_invoicedetail', ['id'], unique=False)
    op.alter_column('app_product', 'created_on',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=True)
    op.alter_column('app_product', 'dct',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               nullable=True)
    op.alter_column('app_product', 'price',
               existing_type=mysql.DECIMAL(precision=7, scale=2),
               nullable=True)
    op.alter_column('app_product', 'tax',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               nullable=True)
    op.create_index(op.f('ix_app_product_id'), 'app_product', ['id'], unique=False)
    op.alter_column('app_product_category', 'created_on',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=True)
    op.create_index(op.f('ix_app_product_category_id'), 'app_product_category', ['id'], unique=False)
    op.alter_column('app_profesional', 'created_on',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=True)
    op.create_index(op.f('ix_app_profesional_id'), 'app_profesional', ['id'], unique=False)
    op.alter_column('app_speciality', 'created_on',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=True)
    op.create_index(op.f('ix_app_speciality_id'), 'app_speciality', ['id'], unique=False)
    op.alter_column('auth_user', 'date_joined',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=True)
    op.alter_column('auth_user', 'email',
               existing_type=mysql.VARCHAR(length=254),
               nullable=True)
    op.alter_column('auth_user', 'first_name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('auth_user', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('auth_user', 'is_staff',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('auth_user', 'is_superuser',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('auth_user', 'last_name',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.alter_column('auth_user', 'password',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('auth_user', 'username',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.drop_index('username', table_name='auth_user')
    op.create_index(op.f('ix_auth_user_id'), 'auth_user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_user_id'), table_name='auth_user')
    op.create_index('username', 'auth_user', ['username'], unique=True)
    op.alter_column('auth_user', 'username',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    op.alter_column('auth_user', 'password',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('auth_user', 'last_name',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    op.alter_column('auth_user', 'is_superuser',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('auth_user', 'is_staff',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('auth_user', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('auth_user', 'first_name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('auth_user', 'email',
               existing_type=mysql.VARCHAR(length=254),
               nullable=False)
    op.alter_column('auth_user', 'date_joined',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=False)
    op.drop_index(op.f('ix_app_speciality_id'), table_name='app_speciality')
    op.alter_column('app_speciality', 'created_on',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=False)
    op.drop_index(op.f('ix_app_profesional_id'), table_name='app_profesional')
    op.alter_column('app_profesional', 'created_on',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=False)
    op.drop_index(op.f('ix_app_product_category_id'), table_name='app_product_category')
    op.alter_column('app_product_category', 'created_on',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=False)
    op.drop_index(op.f('ix_app_product_id'), table_name='app_product')
    op.alter_column('app_product', 'tax',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               nullable=False)
    op.alter_column('app_product', 'price',
               existing_type=mysql.DECIMAL(precision=7, scale=2),
               nullable=False)
    op.alter_column('app_product', 'dct',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               nullable=False)
    op.alter_column('app_product', 'created_on',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=False)
    op.drop_index(op.f('ix_app_invoicedetail_id'), table_name='app_invoicedetail')
    op.alter_column('app_invoicedetail', 'profesional_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('app_invoicedetail', 'product_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('app_invoicedetail', 'price',
               existing_type=mysql.DECIMAL(precision=7, scale=2),
               nullable=False)
    op.alter_column('app_invoicedetail', 'invoice_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_app_invoice_id'), table_name='app_invoice')
    op.alter_column('app_invoice', 'created_on',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=False)
    op.alter_column('app_invoice', 'contact_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_app_contact_id'), table_name='app_contact')
    op.drop_index(op.f('ix_app_contact_date'), table_name='app_contact')
    op.alter_column('app_contact', 'created_on',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=False)
    op.alter_column('app_contact', 'acceptance',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.drop_index(op.f('ix_app_cajadetalle_id'), table_name='app_cajadetalle')
    op.alter_column('app_cajadetalle', 'monto',
               existing_type=mysql.DECIMAL(precision=7, scale=2),
               nullable=False)
    op.alter_column('app_cajadetalle', 'caja_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('app_caja', sa.Column('usuario_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('app_caja_usuario_id_f24ffaeb_fk_auth_user_id', 'app_caja', 'auth_user', ['usuario_id'], ['id'])
    op.drop_index(op.f('ix_app_caja_id'), table_name='app_caja')
    op.drop_index(op.f('ix_app_caja_fecha'), table_name='app_caja')
    op.alter_column('app_caja', 'monto_cierre',
               existing_type=mysql.DECIMAL(precision=7, scale=2),
               nullable=False)
    op.alter_column('app_caja', 'monto_apertura',
               existing_type=mysql.DECIMAL(precision=7, scale=2),
               nullable=False)
    op.alter_column('app_caja', 'created_on',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=False)
    op.drop_index(op.f('ix_app_appointment_id'), table_name='app_appointment')
    op.alter_column('app_appointment', 'speciality_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('app_appointment', 'profesional_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('app_appointment', 'created_on',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=False)
    op.alter_column('app_appointment', 'contact_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_table('django_site',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('domain', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('django_site_domain_a2e37b91_uniq', 'django_site', ['domain'], unique=True)
    op.create_table('django_migrations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('app', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('applied', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('django_content_type',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('app_label', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('model', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('django_content_type_app_label_model_76bd3d3b_uniq', 'django_content_type', ['app_label', 'model'], unique=True)
    op.create_table('auth_group_permissions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='auth_group_permissions_group_id_b120cbf9_fk_auth_group_id'),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='auth_group_permissio_permission_id_84c5c92e_fk_auth_perm'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('auth_group_permissions_group_id_permission_id_0cd325b0_uniq', 'auth_group_permissions', ['group_id', 'permission_id'], unique=True)
    op.create_table('auth_user_groups',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='auth_user_groups_group_id_97559544_fk_auth_group_id'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='auth_user_groups_user_id_6a12ed8b_fk_auth_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('auth_user_groups_user_id_group_id_94350c0c_uniq', 'auth_user_groups', ['user_id', 'group_id'], unique=True)
    op.create_table('auth_user_user_permissions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('auth_user_user_permissions_user_id_permission_id_14a6b632_uniq', 'auth_user_user_permissions', ['user_id', 'permission_id'], unique=True)
    op.create_table('auth_permission',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('content_type_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codename', mysql.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='auth_permission_content_type_id_2f476e4b_fk_django_co'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('auth_permission_content_type_id_codename_01ab375a_uniq', 'auth_permission', ['content_type_id', 'codename'], unique=True)
    op.create_table('auth_group',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'auth_group', ['name'], unique=True)
    op.create_table('django_session',
    sa.Column('session_key', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('session_data', mysql.LONGTEXT(), nullable=False),
    sa.Column('expire_date', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('session_key'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('django_session_expire_date_a5c62663', 'django_session', ['expire_date'], unique=False)
    op.create_table('django_admin_log',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('action_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('object_id', mysql.LONGTEXT(), nullable=True),
    sa.Column('object_repr', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('action_flag', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('change_message', mysql.LONGTEXT(), nullable=False),
    sa.Column('content_type_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='django_admin_log_content_type_id_c4bce8eb_fk_django_co'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='django_admin_log_user_id_c564eba6_fk_auth_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
